# Generated by Django 4.2.7 on 2025-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
